export const SCENE_IDEAS = [
  // --- Cenas Urbanas e Cotidiano ---
  "walking in a city park with a water fountain and pigeons",
  "riding a bicycle in front of a cute European-style cottage",
  "crossing a city street at a crosswalk with cars waiting",
  "buying fresh vegetables at an outdoor market stand",
  "sitting on a park bench eating a triple-scoop ice cream cone",
  "sitting at a round cafe table with a coffee cup and a croissant",
  "walking down a quaint cobblestone street with shops",
  "walking through a toy store aisle filled with teddy bears",
  "shopping in a grocery store with a basket full of fruit",
  "standing at a bus stop waiting for the bus",
  "mailing a letter at a public mailbox",
  "looking at a shop window display with toys",
  "eating a giant slice of pepperoni pizza outside a pizzeria",
  "doing laundry with clothes hanging on a line between buildings",
  "reading a book in a cozy library with tall bookshelves",
  
  // --- Viagem e Aventura ---
  "visiting the Eiffel Tower in Paris taking a selfie",
  "riding a gondola in Venice, Italy",
  "standing in front of the Statue of Liberty in New York",
  "exploring a bustling street market in Tokyo with lanterns",
  "sitting near the Great Pyramid of Giza in Egypt",
  "seeing Big Ben in London",
  "hiking in the mountains with a backpack and map",
  "standing on a bridge near a medieval castle",
  "waiting at a train station with vintage luggage",
  "looking out the window of a passenger train",
  "relaxing on a beach chair under an umbrella with a cold drink",
  "building a large sandcastle on a tropical beach",
  "skiing down a snowy hill with a scarf",
  "camping in the forest with a tent and a campfire",
  
  // --- Fantasia e Profissões ---
  "wearing a space suit and planting a flag on the moon",
  "dressed as a pirate on a wooden ship with a treasure map",
  "piloting a submarine underwater surrounded by fish",
  "dressed as a detective examining footprints with a magnifying glass",
  "dressed as a knight in armor riding a cute pony",
  "doing a science experiment in a lab with beakers",
  "painting a masterpiece on a canvas in an art studio",
  "dressed as a chef baking a cake in a kitchen",
  "dressed as a caveman holding a torch near a baby dinosaur",
  "performing magic tricks as a magician with a top hat",
  "dressed as a firefighter holding a hose",
  "dressed as a doctor with a stethoscope checking a teddy bear",
  "playing a guitar on stage for an audience of animals",
  "dressed as a construction worker with a hard hat and blueprints",
  
  // --- Veículos e Transporte ---
  "flying a vintage propeller airplane over the clouds",
  "driving a steam train locomotive waving from the window",
  "riding in a colorful hot air balloon with birds flying by",
  "driving a futuristic flying car in a sci-fi city",
  "driving a farm tractor in a field with chickens",
  "driving a race car across the finish line",
  "riding a scooter through the neighborhood",
  "skateboarding in a skate park",
  "rowing a small boat on a calm lake",
  
  // --- Natureza e Estações ---
  "walking in an autumn forest with falling leaves and mushrooms",
  "playing in a field of sunflowers with butterflies",
  "hugging a snowman in a winter village scene",
  "exploring a dense jungle with vines and exotic plants",
  "surfing on a wave on a sunny day",
  "snorkeling underwater with a sea turtle",
  "watching the stars through a telescope at night",
  "sleeping on a crescent moon in the night sky",
  "walking in a desert landscape with camels in the background",
  "visiting a zoo with a giraffe and an elephant",
  
  // --- Diversão e Festas ---
  "holding a balloon at a carnival with a ferris wheel behind",
  "balancing on a ball dressed as a circus clown",
  "walking through a candy land with giant lollipops",
  "blowing out candles on a birthday cake with friends",
  "playing soccer on a grass field",
  "flying a kite in a windy meadow",
  "playing with wooden blocks in a playroom",
  "trick-or-treating in a halloween costume with ghosts",
  "opening presents near a Christmas tree",
  "watching fireworks explode in the sky"
];